### ISSUE TITLE
Example for Subscribing to a Topic

### ISSUE THREAD

**Issue by alexmbird** [noisyboiler/wampy#11]
Hey there.  I'm trying to add support to an existing (multithreaded) app for the [Poloniex WAMP API](https://poloniex.com/support/api/).  After a horrible day trying to butcher the Autobahn client into place I happened across Wampy.  It looks like it could be a better fit for my (non-twisted, non-asyncio) needs but I'm struggling to get it up and running.

Could give a simple example of connecting to a WAMP service and subscribing to a topic?

**Comment by nickpollari** [comment]
I am also looking for an alternative to Autobahn for WAMP subscribing to topics. I think I am going to go with wampy. I'll be playing with the code looking for a way to make it work. If I find anything I will report back here, otherwise I will hope to see an update from @noisyboiler or yourself @alexmbird - Thanks

**Comment by noisyboiler** [comment]
hi @alexmbird 
sorry, i've only just seen your message.
and @nickpollari 
thanks for your message too.

I'll update the README asap.

**Comment by nickpollari** [comment]
@noisyboiler 
Thanks for your help. I looked up @alexmbird link and it looks like he needs to connect to: wss://api.poloniex.com

if that is helpful in anyway for the example.
My address is also wss.

Thanks again.

**Comment by alexmbird** [comment]
@noisyboiler smashing, much appreciated.  It will be nice to use something a little more compatible with threading.

**Comment by noisyboiler** [comment]
Thank you both for your comments - they are really appreciated.

I wrote **wampy** because i was not able to get hold of a simple WAMP client and it looks like you both share my frustrations. Autobahn is a monster and all i wanted was a simple WAMP client.

The **wampy** README now at least entertains the idea of subscribers.

@nickpollari 
i had not considered TLS until your comment. I've now begun to think about TLS. And released 0.7.7.x.

@alexmbird 
I'd love to provide an example to help you, but i need a little more context.

both - let me know how i can further improve the ``README``.

Thanks!
